### ISSUE TITLE
Add google scholar to the personnal info header

### ISSUE THREAD

**Issue by paulgoulain** [mintyfrankie/brilliant-CV-Submodule#6]
Hi,

Similar to the PR #5 , I'd like to add Google Scholar to the PersonalInfo header. The problem is that Font Awesome doesn't provide an icon (and likely [never will](https://github.com/FortAwesome/Font-Awesome/issues/541)).
On my personal fork, I added the [academicons](https://jpswalsh.github.io/academicons/) font and load manually the icon.

The thing is, because of the topology of this project with a repo for the awsomeCV which contains the font folder and another for submodule, it isn't clear how I should proceed for making a PR.

Any idea ?

Paul

**Comment by mintyfrankie** [comment]
Hi Paul,

Yes I understand the situation. I was thinking if it would make more sense not to hardcode the key-value pairs of `personalInfo`, by changing it to something like a function:

```
addPersonalInfo(icon=/path/to/icon (or fa-xxx), text="xxx", prefix="https://xx")
```

I've done the template in this way because the original AwesomeCV LaTeX project has also hardcoded this section. While asking users to pass functions allows greater liberty in terms of customized fields and order, it will bring also a breaking change to the existing project, which I am not sure if it is worthy. 

What do you think? If you fancy working on it for a PR, I'd like to review together.

Thanks!

**Comment by mintyfrankie** [comment]
I am closing this issue as it has been stale without further feedback.
